### ISSUE TITLE
Support empty country field when the number is prefixed with +

### ISSUE THREAD

**Issue by fdelapena** [giggsey/libphonenumber-example#1]
libphonenumber can guess the country if the input number starts with a plus sign (+). This is a pretty useful feature from the library and nice to have shown. Here is a hackish demonstration by sending a null character (%00 urlencoded) to the form to circunvent the required country code:

http://giggsey.com/libphonenumber/?phonenumber=%2B50689999999&country=%00

Which will resolve properly the country code by itself.

**Comment by giggsey** [comment]
Quite a bit late, but I've added some help text, and made the Country Code optional (matching what `parse()` actually accepts).

Thanks
