### ISSUE TITLE
ratelimiter.php

### ISSUE THREAD

**Issue by parsibox** [giggsey/libphonenumber-example#10]
ratelimiter.php failed to open stream: No such file or directory

**Comment by meneimoh** [comment]
> ratelimiter.php failed to open stream: No such file or directory

I'm having this error too.

**Comment by Usman78930** [comment]
i'm having this error too.

**Comment by meneimoh** [comment]
I commented the line of code that required the file (ratelimiter.php). Everything worked well. No idea what it does.

**Comment by Usman78930** [comment]
by commenting ratelimiter.php now  i am getting the error Fatal error: Class 'Twig_Environment' not found,

**Comment by meneimoh** [comment]
Everything 'Twig' is view template for the demo. I removed it too. 
Have you checked this https://github.com/giggsey/libphonenumber-for-php  ?

**Comment by Usman78930** [comment]
thanks i have checked the above links and its working perfect.

**Comment by giggsey** [comment]
Hi all,

ratelimiter.php was a script that was added (but never committed) to reduce the number of people scraping the HTML of this demo page to extract their results.

As some of you have realised, commenting out that line sorts that issue.

This project is just code hosting for the demo page of libphonenumber-for-php, it is provided without any support or any guarantee that you can simply clone the project to duplicate it.

It is recommended you follow the documentation found on the libphonenumber-for-php project.

I'll close this issue for now, but leave it unlocked.
