### ISSUE TITLE
AU validation fails with 0441... 0442.. 0443...

### ISSUE THREAD

**Issue by EddyTheDove** [giggsey/libphonenumber-example#6]
Hi,
I tried mobile phone 0454231278 and 0453231278 with the country AU. It fails as an invalid number.

None of the following number works when inserted directly after `04`
41, 42, 43, 45, 46, 53, 54, 60, 61, 62, 63, 64, 65, 71, 80, 83, 86, 92, 93, 94, 95, 96

https://giggsey.com/libphonenumber/?phonenumber=0454231278&country=AU&language=&region=

**Comment by giggsey** [comment]
Please see the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for metadata issues.
